### ISSUE TITLE
nerf2nerf evaluation code

### ISSUE THREAD

**Issue by david2611** [nerf2nerf/nerf2nerf#14]
Hi there.

I was looking to replicate the results from the main nerf2nerf paper and was wondering if you had explicit evaluation code that is used to generate the table of results in Figure 4 of the main paper? 

Can I also check in said table what the 10^2 is meaning? Should error results be multiplied by 10^2 to put them in centimetres or something similar? Just trying to check my understanding when performing my own analysis.

Any help is much appreciated.

**Comment by lilygoli** [comment]
Hi! yes the code for evaluation can be found in [this line](https://github.com/nerf2nerf/nerf2nerf/blob/d1fbae1019a1a41213d249374f3eba6f1f88cdb6/utils.py#L31) where the metrics are logged. 

10^2 in Table 4 means if you divide the numbers in the table by 10^2 you get the actual results (a formatting choice in the paper to avoid too many floating points). The results are not metric (not centimeter), but unit distance in each NeRF reconstruction. Because NeRFs have scale ambiguity in reconstructing a scene, it is not possible to convert this to a metric scale unless the information is provided at the training time.

**Comment by david2611** [comment]
Excellent thanks for the information :+1:
