### ISSUE TITLE
Use for custom datasets

### ISSUE THREAD

**Issue by jmoon0714** [nerf2nerf/nerf2nerf#6]
Hello,

Would you mind sharing a guide and tips to train it for custom data?

Would it be possible to use different teacher model architectures (e.g. instant NGP)? In order for this to possible, what functions are needed besides `call_eval`, `trace_eval`, `transmittance_eval`?

Can you also share how to choose keypoints in keypoints.json?

Thank you!

**Comment by lilygoli** [comment]
Hi!

The code we have provided has only been tested on original completely implicit representations of NeRF, but you should be able to apply it to iNGP style NeRFs, too. In order to use a NeRF model with the code we provided in GitHub, you should hook it up to the nerf_wrapper.py. To do that, you need to save your NeRF model using PyTorch Jit and through that provide the three interfaces needed in the nerf_wrapper.py for your model. These three functions are:
1)  `nerf.call_eval`: this is NeRF’s standard evaluation function (takes in a point and direction and returns the rgb and density of the point)
2) `nerf.transmittance_eval`: this is the interface to an auxiliary network that can be trained along side your NeRF, to store for each point and direction what is the value of transmittance.  In the code we provided we found this network works better if you train it on point positions and camera origin positions (instead of ray direction). In instant-NGP, depending on the repository that you are using there might not be an auxiliary transmittance network, in that case you should add it to the NeRF pipeline and train it on the volume rendering transmittance throughout the NeRF training.
3) `nerf.trace_eval`: this is an interface to the rendering function in your pipeline and takes rays, near/far bound, etc and returns the radiance (and optionally depth). This interface is only used for visualization purposes in our code.

If you provide these three interfaces and the network weights through PyTorch Jit, you should be able to connect your models to our code and run distill.py to get the surface field and so forth. You might also want to change distillation code so you distill into a grid rather than an implicit network to make it even faster. 

General Tip: We found that distilling the surface field is much easier if your objects of interest are not of relatively tiny scale, to avoid that you can upscale your NeRF around a bounding box of the part of the scene that interests you (e.g table top) and use that.

To choose keypoints, you can use any tool that shows you pixel coordinates when hovering the mouse on an image (e.g. Paint app) or you can use Mouse event in python and have a callback to get the pixel coordinates whenever you click on a point on image.

**Comment by lyj9494** [comment]
Hello, thanks for sharing your work!
Could you please sharing your code that defines the three interfaces as well? I’m trying to train nerf2nerf for custom data and want to refer to your code.
Thank you!

**Comment by lilygoli** [comment]
Hi, Thanks for your interest in the work.
We used [this code](https://drive.google.com/file/d/1uqLOoexKDYC7GEsMCzWHimY36tv5A1gU/view?usp=sharing) for our NeRF model. You can find the three interface methods at the bottom of the file.

**Comment by lyj9494** [comment]
Thanks so much!  It helps me a lot.

**Comment by KnightOfTheMoonlight** [comment]
@lilygoli  Thanks for the clarification. I was wondering what's the difference between `torch.save` and `torch.jit.save`?

**Comment by lilygoli** [comment]
`torch.jit.save` is a function of TorchScript that serializes and saves the model like `torch.save`, but has two advanatages for our usecase as it saves an intermidiate representation of a PyTorch model:
1- For loading it you do not need access to the original model's code and architecture to be able to first load the weights into the model and then use the model's methods. You can directly load the model instance itself and call the methods on it. This allows us to write general external scripts that manipulate models with different internal code but same interface (for example different NeRF models with different pipelines).
2- It is in general faster to run evaluation and call methods using the jit saved model as it has gone through some compilation beforehand.

**Comment by KnightOfTheMoonlight** [comment]
> `torch.jit.save` is a function of TorchScript that serializes and saves the model like `torch.save`, but has two advanatages for our usecase as it saves an intermidiate representation of a PyTorch model: 1- For loading it you do not need access to the original model's code and architecture to be able to first load the weights into the model and then use the model's methods. You can directly load the model instance itself and call the methods on it. This allows us to write general external scripts that manipulate models with different internal code but same interface (for example different NeRF models with different pipelines). 2- It is in general faster to run evaluation and call methods using the jit saved model as it has gone through some compilation beforehand.

I see. Thanks!

**Comment by KnightOfTheMoonlight** [comment]
@lilygoli Another question. For custom data collection and preprocess. What data do we need?
I have checked your data folder.
The following data should be collected first:
```
(n2n) sse@CN0316000027L:~/code/nerf2nerf/scenes/scene_2$ tree 
.
├── a
│   ├── 1.json
│   ├── 2.json
│   ├── distilled_a_1.ckpt
│   ├── distilled_a_7.ckpt
│   ├── extracted_pc.json
│   ├── nerf_model_a.pt
│   ├── rgb_1.png
│   └── rgb_2.png
├── b
│   ├── 1.json
│   ├── 2.json
│   ├── distilled_b_1.ckpt
│   ├── extracted_pc.json
│   ├── nerf_model_b.pt
│   ├── rgb_1.png
│   └── rgb_2.png
├── distill_output
│   ├── gt.png
│   └── predicted.png
├── gt_transform.json
├── jar_keypoints.json
├── object_point_clouds
│   ├── jar.json
│   ├── pedestal.json
│   └── pip.json
├── output
│   └── output_transform.npy
├── pedestal_keypoints.json
├── pip_keypoints.json
└── transforms.json
```
From my understanding, there are 
```
trained nerf models for each view
point cloud for each object
keypoint for each object
camera pose for two views of one scene
```
How to get the exact info for all this data?

**Comment by KnightOfTheMoonlight** [comment]
> `torch.jit.save` is a function of TorchScript that serializes and saves the model like `torch.save`, but has two advanatages for our usecase as it saves an intermidiate representation of a PyTorch model: 1- For loading it you do not need access to the original model's code and architecture to be able to first load the weights into the model and then use the model's methods. You can directly load the model instance itself and call the methods on it. This allows us to write general external scripts that manipulate models with different internal code but same interface (for example different NeRF models with different pipelines). 2- It is in general faster to run evaluation and call methods using the jit saved model as it has gone through some compilation beforehand.

Hi, @lilygoli  Another question. Should the `pytorch` and `python` version be the same for `nerf2nerf` repo and the one for the trained and saved by `torch.jit.save`?

**Comment by MiaApr** [comment]
> `torch.jit.save` is a function of TorchScript that serializes and saves the model like `torch.save`, but has two advanatages for our usecase as it saves an intermidiate representation of a PyTorch model: 1- For loading it you do not need access to the original model's code and architecture to be able to first load the weights into the model and then use the model's methods. You can directly load the model instance itself and call the methods on it. This allows us to write general external scripts that manipulate models with different internal code but same interface (for example different NeRF models with different pipelines). 2- It is in general faster to run evaluation and call methods using the jit saved model as it has gone through some compilation beforehand.

hi, thanks for sharing your code! I am trying to save the model through `torch.jit.save` :
```
model = RadianceField(use_coarse=True)
m = torch.jit.script(model)
torch.jit.save(m, path)
```
but  I get an error:

```
torch.jit.frontend.NotSupportedError: Compiled functions can't take variable number of arguments or use keyword-only arguments with defaults:
  File "/root/nerf2nerf/nerf.py", line 424
    def forward(self, *args, method="query", **kwargs):
                                              ~~~~~~~ <--- HERE
        return getattr(self, method)(*args, **kwargs)
```

seems that it is not allowed to use `**kwargs` in the forward() function.  Did you go through the same problem when training and could you please tell me how did you solve it ?
